#1 - Allows setting adaptive content as other statuses
cgkineo/adapt-adaptiveContent pull request #2
Opened 2022-03-21 22:01 UTC by joe-replin

Allows a setting to either mark all adaptive content as complete, optional or unavailable based upon diagnostic assessment results.

2022-09-09 20:29 UTC, joe-replin commented
Fixes #1

2022-09-12 11:52 UTC, oliverfoster requested changes
I notice you're using `"` instead of `'` which probably means you've not got eslint configured correctly.

2022-09-12 11:52 UTC, oliverfoster commented on js/adapt-adaptiveContent.js
> +      model.setOnChildren('_isLocked', false);
setOnChildren is think, takes object syntax
```js
model.setOnChildren({
  _isLocked: false,
  _isComplete: true,
  _isInteractionComplete: true
});
```
Should probably add `_isInteractionComplete` as well.

2022-09-12 11:52 UTC, oliverfoster commented on js/adapt-adaptiveContent.js
> +    };
Would calling `checkContentStatusSetting` here do the same thing?

`setAsUnavailable` is the only one of those three functions that is referenced outside of `checkContentStatusSetting`

You could probably condense to something like:
```js
function checkContentStatusSetting(ids, boolean) {
    if (!ids || ids.length === 0) return;
    const statusOption = Adapt.course.get('_adaptiveContent')._setPageStatusAs;
    const logName = `setAs${statusOption[0].toUpperCase()}${statusOption.substring(1)}`;
    console.log(logName, ids, saveChanges);
    ids.forEach(id => {
      var model = Adapt.findById(id);
      if (!model) return;
      switch (statusOption) {
        case 'unavailable':
          model.setOnChildren('_isAvailable', false);
          break;
        case 'optional':
          model.setOnChildren('_isOptional', true);
          model.set('_classes', model.get('_classes') + " diag-optional");
          break;
        case 'complete':
          model.setOnChildren({
            _isLocked: false,
            _isComplete: true,
            _isInteractionComplete: true
          });
          model.set('_classes', model.get('_classes') + " diag-complete");
          break;
      }
    });
    if (saveChanges) saveToOfflineStorage(ids);
  } 
```

2022-09-12 20:06 UTC, joe-replin commented on js/adapt-adaptiveContent.js
> +    };
Great suggestion. I've updated based upon your recommendation and tested every switch case locally in my project.

2022-09-12 20:08 UTC, joe-replin commented on js/adapt-adaptiveContent.js
> +      model.setOnChildren('_isLocked', false);
Great to know. Thanks.

2022-09-13 06:20 UTC, oliverfoster approved these changes

2022-11-07 16:54 UTC, chris-steele commented on js/adapt-adaptiveContent.js
> +      checkContentStatusSetting([finalAssessmentPageID], saveChanges);
Content will only be made unavailable if that is explicitly requested via config. Just check that is intended? Obviously if you drop this updated code into an existing project the functionality would change if you forgot to amend the config.

2023-01-26 22:59 UTC, joe-replin commented
This has been rebuild as https://github.com/cgkineo/adapt-diagnostic.

2023-01-26 22:59 UTC, closed without merging